### ISSUE TITLE
Does this supports proxy of TF calls to the registry?

### ISSUE THREAD

**Issue by jamengual** [nrkno/terraform-registry#104]
Hi.

If a root module available through this registry instantiates other child modules from remote sources would this be able to handle that case?

For reference: 

https://github.com/hashicorp/terraform/issues/31134

**Comment by stigok** [comment]
No, not currently. We are not editing the source code of the modules at all. Currently, the only remote store implementation we have is through GitHub, and we are simply returning download/source URLs for the modules.

**Comment by jamengual** [comment]
ok, thanks.
