### ISSUE TITLE
Relicense to MIT

### ISSUE THREAD

**Issue by stigok** [nrkno/terraform-registry#389]
Our organisation (NRK) has updated [its guidelines regarding open source software](https://github.com/nrkno/offentlig/blob/main/retningslinjer.md). The current recommendation is to release it under MIT. This requires a re-license of this project. Our organisation's contributors does not need to explicitly consent, however our external contributors do, if we are to reuse/include their code as-is.

A pull request will be opened to follow up on this task later on.

**Comment by pguinard-public-com** [comment]
Sounds great to us!
