### ISSUE TITLE
Support pulling a module version by git branch

### ISSUE THREAD

**Issue by joberget** [nrkno/terraform-registry#61]
An example:

```
source  = "terraform-registry.nrk.cloud/nrkno/nrk-cloud-kubernetes-config/generic//azure-aks?ref=upgrade-ingress-nginx"
```

**Comment by stigok** [comment]
Current work-around is to use plain `git+ssh` URL's to test a specific branch.
```
git::ssh://git@github.com:nrkno/some-repo.git//some-sub-folder?ref=some_commitish
```

**Comment by stigok** [comment]
This is not something that will be pursued right now. Reopen if a good idea to support this arises. But currently we are tied to semver version tags, as Terraform requires this for the module `version` argument.
