### ISSUE TITLE
Support for the provider registry protocol

### ISSUE THREAD

**Issue by sjurtf** [nrkno/terraform-registry#67]
Currently the provider registry protocol is not supported.

It would be a nice addition to support hosting of custom providers.

**Comment by stigok** [comment]
Question is how we would host the providers. They are binary and may require a build stage. Do you have any ideas for how they might be hosted/built/verified?

**Comment by stigok** [comment]
Some issues/questons come to mind.

- Aren't public providers published to the official registry actually submitted to the registry? As opposed to being auto-discovered _by_ the registry?
- Different clients need different binaries, (e.g. linux-arm64, linux-amd64, darwin-amd6 and windows) how do we know what builds we have available?
- How do we get the checksums for the binaries?
- What do we do about signing?

**Comment by sjurtf** [comment]
>Aren't public providers published to the official registry actually submitted to the registry? As opposed to being auto-discovered by the registry?

This is true, but nothing is stopping us from doing auto-discovery of providers based on Github topics, like with modules.

>Different clients need different binaries, (e.g. linux-arm64, linux-amd64, darwin-amd6 and windows) how do we know what builds we have available?

I suggest we follow the same publishing strategy as public providers. This involves a Github Release following a set format. The official publishing strategy provides a GoRelease configuration file that needs to be used.

This ensures that binaries are built and added as assets in a well-known format on the release. We later check the release for what assets are included to know OS and arch values available.

>How do we get the checksums for the binaries?

A file containing checksums is also required to be included as an asset on the Github Release.

>What do we do about signing?

If the provider discovery should be fully automatic, we could require users to include their public key in the repository or the release. It must be somewhere well-known.

An alternative is that users must post their public key to the terraform-registry for each provider. We must then store it somewhere that survives deploys.

**Comment by sjurtf** [comment]
Support merged in #199
